/**
 * Chess set art — the id→appearance map, and it knows NOTHING about the profile.
 *
 * The same split `cards.ts` and `felts.ts` make, for the same reason: this module answers "what
 * does `cs_carved_brown` look like", the GAME asks "what is equipped" (`useEquippedChessSet`), and
 * neither can see the other. A module that could read who is signed in is one a test has to sign
 * in to.
 *
 * WHAT A SET IS. Pieces AND squares together, as one purchase, because that is what a chess set
 * is — a board and the men on it, sold as a pair since forever. Splitting them into two cosmetic
 * kinds would double the store rows to sell the same three combinations, and would let someone
 * assemble a carved-on-blue board that no one designed and that the contrast note below has not
 * been checked against.
 *
 * THE DEFAULT IS THE BOARD THAT ALREADY SHIPPED. `cs_classic` draws Unicode glyphs on
 * `bg-base-300`/`bg-base-200` — byte-for-byte what Chess has drawn since Phase 6 — so it is a free
 * starter, everybody owns it, and an account that buys nothing sees no change at all. `pieces:
 * 'glyph'` is a real variant rather than a null-art fallback: the glyphs are good, they tint by
 * seat (`text-primary`/`text-secondary`), and "the plain one" being a legitimate choice is what
 * stops the free option reading as the broken option.
 *
 * ONE PIECE ART SET, THREE BOARDS. That is what the curated art actually holds, and it is stated
 * rather than padded: three buyable sets share `carved` pieces and differ in their squares. If a
 * second piece style is ever curated in, it is a new `pieces` value and new rows — no shape change.
 */

/** How the men are drawn. `glyph` = the Unicode set; anything else names a folder under `public/chess/`. */
export type ChessPieceArt = 'glyph' | 'carved';

/** The piece letters, in chess notation. `n` is the KNIGHT; `k` is the king. */
export type ChessPieceLetter = 'k' | 'q' | 'r' | 'b' | 'n' | 'p';

/**
 * The solid Unicode men, for the glyph set. Lives HERE rather than in Chess's board because the
 * store previews a glyph set too, and the store may not reach into a game's folder
 * (`@boardwalk/no-cross-game-imports`) — nor should it, since "how a set is drawn" is the set's
 * business, not one screen's. Both renderers import this one map, so a preview cannot show a
 * different king from the board.
 */
export const CHESS_GLYPH: Readonly<Record<ChessPieceLetter, string>> = {
  k: '♚',
  q: '♛',
  r: '♜',
  b: '♝',
  n: '♞',
  p: '♟',
};

export interface ChessSet {
  readonly id: string;
  readonly pieces: ChessPieceArt;
  /**
   * Tailwind background classes for the two square colours, or `null` to keep the theme's own
   * surfaces. `null` rather than a `--color-chess-classic-*` pair, so the default board is
   * literally the same two utilities it always used — see the note in `theme.css`.
   *
   * FULL CLASS STRINGS, never `` `bg-chess-${name}-dark` ``. Tailwind v4 scans source text for
   * complete utility names; an interpolated one is generated by nothing and silently renders no
   * background at all. That is the exact failure `tests/theme-tokens.test.ts` was written for, and
   * writing them out is what keeps these visible to the scanner.
   */
  readonly squares: { readonly dark: string; readonly light: string } | null;
}

/** The free starter — the board Chess has drawn since Phase 6, unchanged. */
export const DEFAULT_CHESS_SET = 'cs_classic';

const SETS: Readonly<Record<string, ChessSet>> = {
  cs_classic: { id: 'cs_classic', pieces: 'glyph', squares: null },
  cs_carved_brown: {
    id: 'cs_carved_brown',
    pieces: 'carved',
    squares: { dark: 'bg-chess-brown-dark', light: 'bg-chess-brown-light' },
  },
  cs_carved_blue: {
    id: 'cs_carved_blue',
    pieces: 'carved',
    squares: { dark: 'bg-chess-blue-dark', light: 'bg-chess-blue-light' },
  },
  cs_carved_green: {
    id: 'cs_carved_green',
    pieces: 'carved',
    squares: { dark: 'bg-chess-green-dark', light: 'bg-chess-green-light' },
  },
};

/** Every registered set, for the store preview and the disk-resolution test. */
export const CHESS_SETS: readonly ChessSet[] = Object.freeze(Object.values(SETS));

/**
 * Resolve an equipped id to a set. Falls back to the STARTER for an unknown or absent id — the
 * card-back rule, not the felt's `null`: a board must always draw. A retired set id left on an
 * account degrades to the classic board rather than to an unstyled grid of missing images.
 */
export function chessSet(id: string | undefined): ChessSet {
  return (id === undefined ? undefined : SETS[id]) ?? SETS[DEFAULT_CHESS_SET]!;
}

/**
 * The image for one piece, or `null` when the set draws glyphs instead.
 *
 * `color` + `type` are the reducer's own `'w' | 'b'` and `PieceType`, so the filename is the piece
 * in chess notation — `wn.png` is a white KNIGHT, not a white king. Deriving the letter from the
 * English word collides on exactly that pair, which is a mistake worth naming because it was made
 * while curating this art: `king` and `knight` both begin with `k`, one silently overwrote the
 * other, and the board rendered a king on both squares.
 *
 * Base-path aware (`import.meta.env.BASE_URL`), like `cardSrc` and `feltSrc` — Pages serves this
 * app from `/Boardwalk/`, so a root-relative path 404s in production and only in production.
 */
export function chessPieceSrc(
  set: ChessSet,
  color: 'w' | 'b',
  type: ChessPieceLetter
): string | null {
  if (set.pieces === 'glyph') return null;
  return `${import.meta.env.BASE_URL}chess/${set.pieces}/${color}${type}.png`;
}
